# Site settings
title: The Opportunity Project
description: The Opportunity Project helps teams use federal open data to build solutions to our nation’s toughest challenges.

contacts:
  mailing-list: https://public.govdelivery.com/accounts/USCENSUS/signup/16610
  census-form: https://www.census.gov/forms/contact-top.html
  email: census.opportunityproject@census.gov
  coil-email: census.openinnovationlabs@census.gov

annual_reports:
  '2020': assets/files/top-annual-report-2020.pdf
  '2019': assets/files/annual_report_2019.pdf

# this ensure that posts with future dates are published
future: true

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
    - "_components/form-controls/*"
    - "_components/form-templates/*"

jekyll_get:
  - data: releases
    json: "https://api.github.com/repos/uswds/uswds/releases"

collections:
  components:
    output: true
    permalink: /:path/
  sprints:
    output: true
    permalink: /sprints/:name/

defaults:
  - scope:
      path: ""
      type: components
    values:
      layout: component
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: "sprints"
    values:
      layout: "sprint"
      class: "sprints"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - DOCS.md
  - critical.css
  - cypress.json
  - federalist.json
  - pa11y.json
  - package.json
  - package-lock.json
  - pages/components.md
  - config
  - js
  - img
  - vendor
  - manifest.yml
  - dependabot.yml
  - node_modules
  - gulpfile.js
  - circle.yml
  - css
