# Site settings
title: The Opportunity Project
description: The Opportunity Project helps teams use federal open data to build solutions to our nation’s toughest challenges.

contacts:
  mailing-list: https://public.govdelivery.com/accounts/USCENSUS/signup/16610
  census-form: https://www.census.gov/forms/contact-top.html
  email: census.opportunityproject@census.gov

annual_report: assets/files/top-annual-report-2020.pdf

# this ensure that posts with future dates are published
future: true

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
    - "_components/form-controls/*"
    - "_components/form-templates/*"

jekyll_get:
  - data: releases
    json: "https://api.github.com/repos/uswds/uswds/releases"

collections:
  components:
    output: true
    permalink: /:path/
  sprints:
    output: true
    permalink: /sprints/:name/

defaults:
  - scope:
      path: ""
      type: components
    values:
      layout: component
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: "sprints"
    values:
      layout: "sprint"
      class: "sprints"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css
