- name: All datasets
  filter: all
- name: Economic Self-Sufficiency
  filter: self-sufficiency
  image: self-sufficiency.jpg
  image-alt: Closeup of desk with two people sitting at laptops and one of them writing on some paperwork
  title: Economic Self-Sufficiency for Low-Income Families
  description: Create digital collaboration platforms that enable low income families to holistically assess their needs and connect with the best federal, state and local programs to equip and empower them toward self-sufficiency and economic mobility.
- name: Refugees
  filter: refugees
  title: Assisting recently resettled refugees
  image: refugee.jpg
  image-alt: White tents in a refugee camp
  description: Create a tool that connects resettled refugees with resources and vital services, such as access to medical care and mental health treatment, English language learning, job training, education, etc. These resources might be available through government agencies, nonprofits, community based organizations, private sector actors and the like.
- name: Rural Development
  filter: sustainable-rural-development
  image: farm.jpg
  image-alt: birdseye view of a farm
  title: Facilitating Sustainable Rural Economic Development
  description: Create digital tools that help rural communities access and use data to implement solutions to economic, environmental, and human health challenges, taking care to reach places that have limited professional capacity and small budgets.
- name: Emergency Funding
  filter: disaster-spending
  image: flood.jpg
  image-alt: Flooded street with cars and a building in the background
  title: Tracking impact of disaster and emergency funding
  description: Create digital tools and resources to track federal financial assistance award spending starting from Federal awards and flowing down to state and/or local spend in response to one or more emergencies and disasters (e.g., COVID-19 Coronavirus pandemic, hurricanes, earthquakes, and other disasters)
