topics:
  - Addressing
  - Census
  - Disasters
  - Discovery
  - Economic Development
  - Education
  - Employment
  - Entrepreneurship
  - Environment
  - Grants
  - Health
  - Housing
  - Opioids
  - Refugees
  - Rural
  - Transportation
  - Veterans
years:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
agencies:
  - Census Bureau
  - Environmental Protection Agency
  - Department of Agriculture
  - Department of Education
  - Department of Health and Human Services
  - Department of Homeland Security
  - Department of Housing and Urban Development
  - Department of Labor
  - Department of State
  - Department of the Treasury
  - Department of Transportation
  - Department of Veterans Affairs
  - Economic Development Administration
  - Federal Emergency Management Agency
  - Forest Service
  - Office of Management and Budget
  - Office of the U.S. Surgeon General
  - The Wilson Center
  - USA for UNHCR
  - White House Council of Economic Advisors
  - White House Office of Science and Technology Policy
